### ISSUE TITLE
Maildump install fails on Python 3

### ISSUE THREAD

**Issue by cdw9** [sixfeetup/bobtemplates.sixfeetup#11]
`maildump` is in the requirements.txt, but installation fails on Python 3. We may need to add a condition to it, or remove it for now.

**Comment by abosio** [comment]
Installation works for me on Python 3.7. However, when it is present, buildout produces this error.

```
Installing plonesite.
. . . . . . . . . . .
daemon manager not running
Traceback (most recent call last):
  File "/Users/abosio/Documents/bobtest/myproject8/parts/instance1/bin/interpreter", line 281, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "/Users/abosio/.buildout/eggs/Zope-4.6.3-py3.7.egg/Zope2/__init__.py", line 18, in <module>
    from zope.deferredimport import deprecated
ModuleNotFoundError: No module named 'zope.deferredimport'
daemon manager not running
```

zope.deferredimport is present in the omelette.

maildump brings gevent. gevent bring zope.event and zope.interface. Uninstalling zope.event seems to make the error during buildout go away, but I'm not sure about root cause. I could sorta understand how having a second zope.something in the virtualenv could maybe interfere with the one inside the buildout, but not seeing how we get to the error above, which does not refer to zope.event.

I'm going to remove maildump. Maybe we should run mailhog in docker since that is what we prefer for other projects and deploy it with salt or terraform or whatever.

Dependency tree for future reference.
```
maildump==1.0
  - beautifulsoup4 [required: Any, installed: 4.10.0]
    - soupsieve [required: >1.2, installed: 2.3.1]
  - Flask [required: Any, installed: 2.0.2]
    - click [required: >=7.1.2, installed: 8.0.3]
      - importlib-metadata [required: Any, installed: 4.10.0]
        - typing-extensions [required: >=3.6.4, installed: 4.0.1]
        - zipp [required: >=0.5, installed: 3.7.0]
    - itsdangerous [required: >=2.0, installed: 2.0.1]
    - Jinja2 [required: >=3.0, installed: 3.0.3]
      - MarkupSafe [required: >=2.0, installed: 2.0.1]
    - Werkzeug [required: >=2.0, installed: 2.0.2]
  - gevent [required: Any, installed: 21.12.0]
    - greenlet [required: >=1.1.0,<2.0, installed: 1.1.2]
    - setuptools [required: Any, installed: 45.3.0]
    - zope.event [required: Any, installed: 4.5.0]
      - setuptools [required: Any, installed: 45.3.0]
    - zope.interface [required: Any, installed: 5.4.0]
      - setuptools [required: Any, installed: 45.3.0]
  - html5lib [required: Any, installed: 1.1]
    - six [required: >=1.9, installed: 1.16.0]
    - webencodings [required: Any, installed: 0.5.1]
  - lockfile [required: Any, installed: 0.12.2]
  - Logbook [required: Any, installed: 1.5.3]
  - passlib [required: Any, installed: 1.7.4]
  - python-daemon [required: Any, installed: 2.3.0]
    - docutils [required: Any, installed: 0.18.1]
    - lockfile [required: >=0.10, installed: 0.12.2]
    - setuptools [required: Any, installed: 45.3.0]
  - pytz [required: Any, installed: 2021.3]
```
